Repository pytorch/TensorRT, pull requests merged in 2022-06, with the labels that each got.

#1106 format by buildifier
  tests/core/partitioning/partitioning_test.bzl
Labels: component: tests, cla signed

#1107 fx2trt] Modify lower setting class to accommandate AIT lowering
  py/torch_tensorrt/fx/lower_setting.py
Labels: component: api [Python], cla signed, fx

#1102 Modified the notebooks directory's README file
  notebooks/README.md
Labels: documentation, cla signed

#1118 [FX] Sync to OSS
  py/torch_tensorrt/fx/lower.py
  py/torch_tensorrt/fx/lower_setting.py
  py/torch_tensorrt/fx/passes/lower_basic_pass.py
  py/torch_tensorrt/fx/test/tracer/test_acc_tracer.py
  py/torch_tensorrt/fx/tracer/acc_tracer/acc_ops.py
Labels: component: api [Python], cla signed, component: fx, fx

#1120 [fx_acc] Add acc_tracer support for torch.mm
  docs/v1.1.0/._index.html
  py/torch_tensorrt/fx/tracer/acc_tracer/acc_ops.py
Labels: component: api [Python], cla signed, component: fx, fx

#1126 amending triton deployment docs
  docsrc/index.rst
  docsrc/tutorials/serving_torch_tensorrt_with_triton.rst
Labels: documentation, cla signed

#1099 fix: Fix keep_dims functionality for aten::max
  core/conversion/converters/impl/max.cpp
  tests/core/conversion/converters/test_reduce.cpp
Labels: component: tests, component: conversion, component: core, component: converters, cla signed

#1055 feat(//tests): Update rtol and atol based tolerance for test cases
  tests/util/util.cpp
  tests/util/util.h
Labels: component: tests, cla signed

#1090 doc: add the explanation for partition phases on docs
  docsrc/contributors/partitioning.rst
Labels: documentation, cla signed

#1052 feat (//cpp): Using atol and rtol based tolerance threshold for torchtrtc
  cpp/bin/torchtrtc/README.md
  cpp/bin/torchtrtc/accuracy.cpp
  cpp/bin/torchtrtc/accuracy.h
  cpp/bin/torchtrtc/main.cpp
  docsrc/tutorials/torchtrtc.rst
Labels: documentation, component: api [C++], cla signed

#1137 CI/CD setup
  .circleci/config.yml
  WORKSPACE.ci
  py/setup.py
Labels: component: build system, component: api [Python], cla signed, component: fx, fx

#1142 Update README.md
  README.md
Labels: cla signed

#1098 fixed typos
  notebooks/CitriNet-example.ipynb
  notebooks/EfficientNet-example.ipynb
  notebooks/Hugging-Face-BERT.ipynb
  notebooks/dynamic-shapes.ipynb
  notebooks/lenet-getting-started.ipynb
  notebooks/ssd-object-detection-demo.ipynb
  notebooks/vgg-qat.ipynb
Labels: documentation, cla signed

#1147 [FX] --fx-only does not need to check bazel
  py/setup.py
Labels: component: api [Python], cla signed

#1141 [FX] refactor the fx path in compile function
  py/torch_tensorrt/_compile.py
  py/torch_tensorrt/fx/example/fx2trt_example.py
  py/torch_tensorrt/fx/example/lower_example.py
  py/torch_tensorrt/fx/example/test_fx2trt.py
  py/torch_tensorrt/fx/example/torch_trt_simple_example.py
  py/torch_tensorrt/fx/fx2trt.py
  py/torch_tensorrt/fx/lower.py
  py/torch_tensorrt/fx/lower_setting.py
Labels: component: api [Python], cla signed, component: fx, fx

#1145 Create getting_started_with_fx_path.rst
  docsrc/index.rst
  docsrc/tutorials/getting_started_with_fx_path.rst
  notebooks/getting_started_with_fx_path_lower_to_trt.ipynb
  notebooks/getting_started_with_fx_path_module.ipynb
  py/setup.py
Labels: documentation, component: api [Python], cla signed
