Repository pytorch/TensorRT, pull requests merged in 2023-11, with the labels that each got.

#2426 feat/fix: Add new models, fix perf scripts
  .github/workflows/docker_builder.yml
  tools/perf/benchmark.sh
  tools/perf/custom_models.py
  tools/perf/hub.py
  tools/perf/perf_run.py
  tools/perf/requirements.txt
  tools/perf/utils.py
Labels: cla signed

#2428 fix: Upgrade perf benchmark system
  tools/perf/benchmark.sh
  tools/perf/hub.py
  tools/perf/models/.gitkeep
  tools/perf/perf_run.py
  tools/perf/utils.py
Labels: cla signed

#2402 feat: support tile dynamo converter
  py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
  py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
  tests/py/dynamo/conversion/test_tile_aten.py
Labels: component: tests, component: conversion, component: converters, component: api [Python], cla signed, component: dynamo

#2423 chore: update perf tooling to add dynamo options
  .github/workflows/docker_builder.yml
  tools/perf/README.md
  tools/perf/benchmark.sh
  tools/perf/config/vgg16.yml
  tools/perf/config/vgg16_trt.yml
  tools/perf/custom_models.py
  tools/perf/hub.py
  tools/perf/models/.gitkeep
  tools/perf/perf_run.py
  tools/perf/requirements.txt
  tools/perf/utils.py
Labels: cla signed

#2430 feat: Add `aten.unbind` decomposition for VIT
  py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
Labels: component: lowering, component: api [Python], cla signed, component: dynamo

#2432 fix: Segfault fix for Benchmarks
  .circleci/config.yml
  README.md
  WORKSPACE
  dev_dep_versions.yml
  docker/README.md
  tools/perf/perf_run.py
  tools/perf/utils.py
Labels: component: build system, cla signed

#2417 examples: Stable Diffusion `torch.compile` sample with output image
  docsrc/index.rst
  docsrc/tutorials/images/majestic_castle.png
  examples/dynamo/README.rst
  examples/dynamo/torch_compile_stable_diffusion.py
Labels: documentation, cla signed

#2433 cherry-pick/fix: Performance benchmarking fixes and Torch version fix
  .circleci/config.yml
  .github/workflows/docgen.yml
  .github/workflows/docker_builder.yml
  README.md
  WORKSPACE
  dev_dep_versions.yml
  docker/README.md
  docker/dist-build.sh
  docsrc/index.rst
  docsrc/tutorials/images/majestic_castle.png
  examples/dynamo/README.rst
  examples/dynamo/torch_compile_stable_diffusion.py
  py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
  py/torch_tensorrt/dynamo/lowering/passes/constant_folding.py
  tools/perf/README.md
  tools/perf/benchmark.sh
  tools/perf/config/vgg16.yml
  tools/perf/config/vgg16_trt.yml
  tools/perf/custom_models.py
  tools/perf/hub.py
  tools/perf/models/.gitkeep
  tools/perf/perf_run.py
  tools/perf/requirements.txt
  tools/perf/utils.py
Labels: documentation, component: lowering, component: build system, component: api [Python], cla signed, component: dynamo

#2437 minor fix: Parse out slashes in Docker container name
  .github/workflows/docker_builder.yml
Labels: cla signed

#2425 Cherry pick 2420 to release/2.1
  docsrc/conf.py
  docsrc/contributors/dynamo_converters.rst
  docsrc/contributors/fx_converters.rst
  docsrc/contributors/ts_converters.rst
  docsrc/dynamo/dynamo_export.rst
  docsrc/dynamo/torch_compile.rst
  docsrc/fx/getting_started_with_fx_path.rst
  docsrc/getting_started/installation.rst
  docsrc/index.rst
  docsrc/py_api/dynamo.rst
  docsrc/py_api/torch_tensorrt.rst
  docsrc/ts/creating_torchscript_module_in_python.rst
  docsrc/ts/getting_started_with_cpp_api.rst
  docsrc/ts/getting_started_with_python_api.rst
  docsrc/ts/torchscript_frontend_from_pytorch.rst
  docsrc/user_guide/dynamic_shapes.rst
  docsrc/user_guide/saving_models.rst
  py/torch_tensorrt/_compile.py
  py/torch_tensorrt/dynamo/__init__.py
  py/torch_tensorrt/dynamo/_compiler.py
  py/torch_tensorrt/dynamo/_exporter.py
  py/torch_tensorrt/dynamo/_tracer.py
  py/torch_tensorrt/dynamo/backend/backends.py
  py/torch_tensorrt/dynamo/conversion/_ConverterRegistry.py
  py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
  py/torch_tensorrt/dynamo/conversion/__init__.py
  py/torch_tensorrt/dynamo/conversion/_conversion.py
  py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
  py/torch_tensorrt/dynamo/conversion/converter_utils.py
  py/torch_tensorrt/dynamo/conversion/impl/cast.py
  py/torch_tensorrt/dynamo/conversion/ops_evaluators.py
  py/torch_tensorrt/dynamo/conversion/prims_ops_converters.py
  py/torch_tensorrt/dynamo/lowering/__init__.py
  py/torch_tensorrt/dynamo/partitioning/_adjacency_partitioner.py
  py/torch_tensorrt/dynamo/partitioning/_global_partitioner.py
  py/torch_tensorrt/dynamo/tools/opset_coverage.py
  py/torch_tensorrt/dynamo/utils.py
  tests/py/dynamo/models/test_export_serde.py
Labels: documentation, component: tests, component: lowering, component: conversion, component: converters, component: api [Python], cla signed, fx, component: dynamo, component: torch_compile

#2438 cherry-pick/minor fix: Parse out slashes in Docker container name (#2437)
  .github/workflows/docker_builder.yml
Labels: cla signed

#2440 fix: Docs rendering on PyTorch site
  .github/workflows/docker_builder.yml
  docsrc/index.rst
Labels: documentation, priority: high, cla signed

#2396 Numpy changes for aten::index converter
  py/torch_tensorrt/dynamo/conversion/converter_utils.py
  py/torch_tensorrt/dynamo/conversion/impl/select.py
  tests/py/dynamo/conversion/test_index_aten.py
Labels: component: tests, component: conversion, component: converters, component: api [Python], cla signed, component: dynamo

#2411 feat: a lowering pass to re-compose ops into aten.linear
  py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
  py/torch_tensorrt/dynamo/conversion/impl/__init__.py
  py/torch_tensorrt/dynamo/conversion/impl/addmm.py
  py/torch_tensorrt/dynamo/lowering/_decompositions.py
  py/torch_tensorrt/dynamo/lowering/passes/_aten_lowering_pass.py
  py/torch_tensorrt/dynamo/lowering/passes/lower_efficient_attention.py
  py/torch_tensorrt/dynamo/lowering/passes/lower_linear.py
  tests/py/dynamo/conversion/test_addmm_aten.py
  tests/py/dynamo/lowering/test_aten_lowering_passes.py
  tests/py/dynamo/lowering/test_decompositions.py
Labels: component: tests, component: lowering, component: conversion, component: converters, component: api [Python], cla signed, component: dynamo

#2448 chore: fix docs for export [release/2.1]
  docsrc/dynamo/dynamo_export.rst
  docsrc/user_guide/dynamo_export.rst
  docsrc/user_guide/saving_models.rst
  py/torch_tensorrt/dynamo/_exporter.py
Labels: documentation, component: build system, component: api [Python], component: api [C++], cla signed, fx, component: dynamo

#2447 chore: fix docs for export
  docsrc/dynamo/dynamo_export.rst
  docsrc/user_guide/saving_models.rst
  py/torch_tensorrt/dynamo/_exporter.py
Labels: documentation, component: api [Python], cla signed, component: dynamo

#2446 chore: add additional BN native converter
  py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
  py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
  tests/py/dynamo/conversion/test_batch_norm_aten.py
Labels: component: tests, component: lowering, component: conversion, WIP, component: api [Python], cla signed, component: dynamo

#2453 minor fix: Update Benchmark values
  tools/perf/benchmark.sh
Labels: cla signed

#2452 chore: add additional native BN converter (cherry-pick of #2446)
  py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
  py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
  tests/py/dynamo/conversion/test_batch_norm_aten.py
Labels: component: tests, component: lowering, component: conversion, component: api [Python], cla signed, fx, component: dynamo

#2441 cherry-pick/fix: Docs rendering on PyTorch site (#2440)
  .github/workflows/docker_builder.yml
  docsrc/index.rst
Labels: documentation, cla signed

#2454 minor fix: Update Benchmark values (#2453)
  tools/perf/benchmark.sh
Labels: cla signed

#2456 Delete .circleci directory
  .circleci/config.yml
Labels: cla signed

#2466 fix: Wrap perf benchmarks with no_grad
  tools/perf/accumulate_results.py
  tools/perf/benchmark.sh
  tools/perf/perf_run.py
Labels: cla signed

#2470 cherry-pick: Wrap perf benchmarks with no_grad (#2466)
  tools/perf/accumulate_results.py
  tools/perf/benchmark.sh
  tools/perf/perf_run.py
Labels: cla signed

#2472 chore: Upgrade `release` to Torch 2.1.1
  README.md
  WORKSPACE
  py/requirements.txt
Labels: component: build system, component: api [Python], cla signed

#2463 fix: Bug in slice operator with default inputs
  py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
  py/torch_tensorrt/dynamo/conversion/converter_utils.py
  py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
  tests/py/dynamo/conversion/test_slice_aten.py
Labels: component: tests, component: conversion, priority: high, component: converters, component: api [Python], cla signed, component: dynamo

#2290 Expose IGridSampleLayer
  py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
  py/torch_tensorrt/dynamo/conversion/impl/__init__.py
  py/torch_tensorrt/dynamo/conversion/impl/grid.py
  tests/py/dynamo/conversion/test_grid_aten.py
Labels: component: tests, component: conversion, component: converters, component: api [Python], cla signed, component: dynamo

#2429 feat: support more elementwise and unary dynamo converters
  py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
  py/torch_tensorrt/dynamo/conversion/impl/elementwise/base.py
  py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
  py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
  tests/py/dynamo/conversion/test_bitwise_and_aten.py
  tests/py/dynamo/conversion/test_bitwise_not_aten.py
  tests/py/dynamo/conversion/test_bitwise_or_aten.py
  tests/py/dynamo/conversion/test_bitwise_xor_aten.py
  tests/py/dynamo/conversion/test_eq_aten.py
  tests/py/dynamo/conversion/test_ge_aten.py
  tests/py/dynamo/conversion/test_gt_aten.py
  tests/py/dynamo/conversion/test_le_aten.py
  tests/py/dynamo/conversion/test_lt_aten.py
  tests/py/dynamo/conversion/test_ne_aten.py
Labels: component: tests, component: conversion, component: converters, component: api [Python], cla signed, component: dynamo

#2477 fix: Naming issue in opset coverage tool
  py/torch_tensorrt/dynamo/tools/opset_coverage.py
Labels: component: api [Python], cla signed, component: dynamo

#2500 cherry-pick: View and slice bugfixes
  py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
  py/torch_tensorrt/dynamo/conversion/converter_utils.py
  py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
  py/torch_tensorrt/dynamo/lowering/passes/_aten_lowering_pass.py
  py/torch_tensorrt/dynamo/lowering/passes/view_to_reshape.py
  tests/py/dynamo/conversion/test_slice_aten.py
  tests/py/dynamo/lowering/test_aten_lowering_passes.py
Labels: component: tests, component: lowering, component: conversion, component: converters, component: api [Python], cla signed, component: dynamo

#2503 chore: Add TRT runner via onnx
  tools/perf/benchmark.sh
  tools/perf/perf_run.py
  tools/perf/requirements.txt
Labels: cla signed
